### PR TITLE
Added Oracle12c Dialect

### PR DESCRIPTION
**Pull request by mijaved**
**New Feature:**
- Added support for OffsetFetch
- Added Tests for Oracle12c dialect

**Fixes:**
- Replace `Except` with Oracle Equivalent keyword `Minus`

### CODE REVIEW

**Comment by mijaved** [comment]
Temporarily closing for further test

**Comment by dfaruque** [comment]
Thank you very much @mijaved. it will be very helpful for the serenity community.

**Comment by mijaved** [comment]
Reopening after fixing `Skip` without `Take ` issue

**Comment by volkanceylan** [comment]
Thanks for your pull request and tests. There are a few points that needs to be clarified.

First, we can't change the default dialect to 12c as this would be a breaking change for existing users of Serenity who use an older Oracle version.

Second issue is we need to discuss why had to modify SqlQuery_ToString method, and why had to check for ServerType there? If that is really needed (e.g. not just a personal preference to use OFFSET FETCH there instead of SKIP) we would have to add some setting to dialect classes (yes it would be a breaking change for users with custom dialects but willing to accept that).

And, must make sure that this doesn't bring any breaking changes to users of other database types / Oracle versions.

Oracle dialect was hardest for me, possibily due to my lack of Oracle knowledge, but i just want to make sure this won't break anything, as i don't want to go back into installing Oracle and troubles i had :)

**Comment by mijaved** [comment]
Agreed on the first issue on default dialect and resolve that on commit e47810e
In fact, I did that because SQL Server default dialect is also assigned with the latest version 
`{ "System.Data.SqlClient", SqlServer2012Dialect.Instance },`

Regarding the Second issue,
I tried my best not to change any code in SqlQuery_ToString.cs class 2fda578, but it was not working for the first-page request from any data grid since first paged request always request for skip = 0 and take = [pagesize], which was generating the traditional query with ROW_OVER() and costing our application by taking unusual time to load data.

Then I tried to fix that by adding Take > 0 directly
`useOffset = (skip > 0 || take > 0) && !useSkipKeyword && dialect.CanUseOffsetFetch;`
this was also failing some Sql Server and SqlLite tests where TakeKeyWord Top and Limit were used.

Since Oracle does not have any independent TakeKeyWord like TOP and LIMIT, I had to impose the Offset Fetch. However, this ServerType check will not have any impact on the previous version of Oracle since it also checks CanUseOffsetFetch which true for Oracle12C dialect only
`if (dialect.ServerType.Equals("Oracle")) {  
    useOffset = (skip > 0 || take > 0) && !useSkipKeyword && dialect.CanUseOffsetFetch;
}`

**Comment by dfaruque** [comment]
@volkanceylan We are using oracle in our project with this fix as a custom build. There are no breaking changes we observe yet by this pull request. So, you may consider to merge it.

**Comment by dfaruque** [comment]
Waiting for this to merge.

**Comment by volkanceylan** [comment]
I manually merged this but used another way for now. 588f3eb2ce36d77545d7ef124df6c9c772c57cf5

**Pull request merged**
