### PR TITLE
TimeSpanEditor and ButtonEditor

### PR DESCRIPTION
**Pull request by Estrusco**
Use TimeSpanEditor with TimeSpanField and time(7) type in SQL, or with string.

Use ButtonEditor, with client side onClick delegate like: 

```ts
this.form.myFormBtn.onClick = (e) => {
    Q.notifyInfo("OK");
};
```

### CODE REVIEW

**Comment by dfaruque** [comment]
NICE!

**Comment by 4bitsteams** [comment]
wow nice

**Comment by JohnRanger** [comment]
Yeah - cool.

**Comment by marcobisio** [comment]
thanks @Estrusco !

**Comment by osmanaslancan** [comment]
we'll reconsider these using flatpickr or another solution

**Pull request closed without merging**
