### PR TITLE
UploadBehavior refinements

### PR DESCRIPTION
**Pull request by furkanevran**
rename ImageUploadBehavior to FileUploadBehavior
rename MultipleImageUploadBehavior to MultipleFileUploadBehavior
create two new classes named ImageUploadBehavior and MultipleImageUploadBehavior for backwards compatibility
create new interfaces to use with upload behaviors
use newly created abstractions for upload behavior's activating attributes
add abstract and interface check to AddBehaviorAttribute

this PR allows running FileUploadBehavior and MultipleFileUploadBehavior with custom editors (by inheriting the new interfaces from the auto-generated partial editor attributes)

### CODE REVIEW

**Comment by furkanevran** [comment]
this pr will be refactored more

**Comment by volkanceylan** [comment]
Could you please also handle new properties ThumbBackColor and ScaleBackColor

**Review by volkanceylan — APPROVED** [review]
Great job, thanks Furkan!

**Review by volkanceylan — APPROVED** [review]
thanks again!

**Pull request merged**
