### PR TITLE
MvcCommand updated

### PR DESCRIPTION
**Pull request by deveracs**
Error generating Mvc const string:
Test:
Modules\FolderOne\FolderA\ParameterIndex.cshtml
Modules\FolderTwo\FolderA\ParameterIndex.cshtml

            //Error: 
            public static class FolderOne
            {
              public static class FolderA
              {
                  public const string ParameterIndex = "...";
                  public const string ParameterIndex = "...";

### CODE REVIEW

**Comment by volkanceylan** [comment]
Sorry @deveracs for late reply, are you sure current version generates such duplicate constants in FolderA when you have two files in different folders, e.g. FolderOne FolderTwo?

**Comment by deveracs** [comment]
Yes, CodeGenerator 3.9.8 result:

```
public static class Parametro
            {
                public const string ParametroIndex = "~/Modules/Inmovilizados/Parametro/ParametroIndex.cshtml";
                public const string ParametroIndex = "~/Modules/Iva/Parametro/ParametroIndex.cshtml";
            }
```

> Error	CS0102	El tipo 'Views.Inmovilizados.Parametro' ya contiene una definición para 'ParametroIndex'

**Comment by volkanceylan** [comment]
@VictorTomaili please try to reproduce this

**Comment by VictorTomaili** [comment]
It's can not reproduced.

**Comment by volkanceylan** [comment]
Can't reproduce

**Pull request closed without merging**
